### ISSUE TITLE
Errors running plugin

### ISSUE THREAD

**Issue by CraigBurden** [snhobbs/kicad-testpoints-pcm#6]
![Screenshot_20240704_151546](https://github.com/snhobbs/kicad-testpoints-pcm/assets/5887357/00dac708-98d5-459a-8cbf-f649c7359ea3)

There appears to be a type conversion error somewhere in the plug-in, all I did was try to run the plug in

**Comment by snhobbs** [comment]
Huh, didn't know the aux origin could return a string. I'll add a catch for that. How did you have the origin set? I'd like to try to replicate the error. 
Thanks!

**Comment by thisisgregm** [comment]
Same here. Different errors though.

I'm on Win11 + KiCad 9.0.5.

Installed the plugin, tried to run it from the top bar icon and a popup with an error message comes up:


`Exception on python action plugin code X 

Traceback (most recent call last):

File "C:\Users\xxxxx\Documents\KiCad\9.0\3rdparty\\plugins\com_github_TheJigsApp_kicad-parts-placer-pcm\plugin.py", line 418, in Run
dig = MyDialog(get_gui_frame(name="PcbFrame"), title=Meta.title) 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users\xxxxx\Documents\KiCad\9.0\3rdparty\\plugins\com_github_TheJigsApp_kicad-parts-placer-pcm\plugin.py", line 359, in __init__
about_panel = AboutPanel(notebook)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

File "C:\Users\xxxxx\Documents\KiCad\9.0\3rdparty\\plugins\com_github_TheJigsApp_kicad-parts-placer-pcm\plugin.py", line 305, in __init__
for key, value in kicad_parts_placer_._header_pseudonyms.items(): 
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

AttributeError: module 'kicad_parts_placer_' has no attribute '_header_pseudonyms'
`

**Comment by snhobbs** [comment]
Same issue, different plugin I'm afraid. I'll put in a pull request, in the mean time here's the parts placer plugin packet: https://github.com/snhobbs/kicad-parts-placer-pcm/releases/tag/v0.1.14

**Comment by thisisgregm** [comment]
Indeed, sorry. Didn't spot that. My bad.
Not sure it this is good place to discuss it. I updated the plugin. I can run it, select csv file, but pressing Submit doesn't do anything.
Can you help? What other into do you need to fix it?

**Comment by snhobbs** [comment]
The parts placer plugin repo is this one: https://github.com/snhobbs/kicad-parts-placer-pcm
Could you open an issue there and mention your OS, KICAD version, and install method (snap, flatpak, repo, ...). 
Thanks!
